version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nX2o4s8WF8fSpZca
      POSTGRES_DB: financial_planner
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=severally-pro-minivet.data-1.use1.tembo.io;Database=financial_planner;Username=postgres;Password=nX2o4s8WF8fSpZca
    ports:
      - "80:80"
    depends_on:
      - db

volumes:
  postgres_data:
